In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
digits = load_digits()

In [4]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [6]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9537037037037037

In [7]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.987037037037037

In [8]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9722222222222222

In [9]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)

In [10]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [11]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [12]:
get_score(SVC(),X_train, X_test, y_train, y_test)

0.987037037037037

In [13]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold()

In [14]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index],\
                                       digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(),X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(),X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(),X_train, X_test, y_train, y_test))

In [15]:
scores_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [16]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [17]:
scores_rf

[0.9315525876460768, 0.9582637729549248, 0.9365609348914858]

In [18]:
from sklearn.model_selection import cross_val_score

In [19]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93055556, 0.91388889, 0.95264624, 0.96935933, 0.93593315])